"""
Build Visa Navigator model artifacts from the H1B Sponsorship Analytics dataset.

Expected input:
  data/h1b_engineered_features.csv

That file is generated by the H1B-Sponsorship-Analytics project and is ignored by
git in this repository. The backend only needs the compact model and lookup
artifacts produced by this script.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    mean_absolute_error,
    mean_squared_error,
    precision_recall_fscore_support,
    r2_score,
    roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBRegressor


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "h1b_engineered_features.csv"
MODEL_DIR = ROOT / "backend" / "models"
LOOKUPS_DIR = ROOT / "backend" / "lookups"

RISK_FEATURES = [
    "fiscal_year",
    "log_petitions",
    "initial_share",
    "continuation_share",
    "missing_state_flag",
    "missing_naics_flag",
    "state",
]

REGRESSION_FEATURES = [
    "fiscal_year",
    "total_cases",
    "log_petitions",
    "initial_share",
    "continuation_share",
    "missing_state_flag",
    "missing_naics_flag",
    "industry_mean_rate",
    "industry_std",
    "industry_cv",
    "industry_employer_count",
    "industry_total_cases",
    "state",
]


NAICS_LABELS = {
    11: "Agriculture, Forestry, Fishing and Hunting",
    21: "Mining, Quarrying, and Oil and Gas Extraction",
    22: "Utilities",
    23: "Construction",
    31: "Manufacturing (Food, Textile, Apparel)",
    32: "Manufacturing (Wood, Paper, Chemical)",
    33: "Manufacturing (Metal, Machinery, Electronics)",
    42: "Wholesale Trade",
    44: "Retail Trade",
    45: "Retail Trade (Sporting, Hobby, General)",
    48: "Transportation and Warehousing",
    49: "Transportation and Warehousing (Postal, Courier)",
    51: "Information",
    52: "Finance and Insurance",
    53: "Real Estate and Rental and Leasing",
    54: "Professional, Scientific, and Technical Services",
    55: "Management of Companies and Enterprises",
    56: "Administrative and Support Services",
    61: "Educational Services",
    62: "Health Care and Social Assistance",
    71: "Arts, Entertainment, and Recreation",
    72: "Accommodation and Food Services",
    81: "Other Services",
    92: "Public Administration",
    99: "Unclassified",
}


def load_dataset() -> pd.DataFrame:
    if not DATA_PATH.exists():
        raise FileNotFoundError(
            f"Missing {DATA_PATH}. Copy h1b_engineered_features.csv from "
            "H1B-Sponsorship-Analytics/data/processed/ before running this script."
        )

    df = pd.read_csv(DATA_PATH)
    df = df[df["approval_risk_tier"].notna()].copy()
    df["state"] = df["state"].fillna("UNKNOWN").astype(str).str.upper()
    df["naics"] = pd.to_numeric(df["naics"], errors="coerce").astype("Int64")
    return df


def make_preprocessor(feature_cols: list[str]) -> ColumnTransformer:
    categorical = [col for col in feature_cols if col == "state"]
    numeric = [col for col in feature_cols if col not in categorical]

    return ColumnTransformer(
        transformers=[
            (
                "num",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="median")),
                        ("scaler", StandardScaler()),
                    ]
                ),
                numeric,
            ),
            (
                "cat",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        ("onehot", OneHotEncoder(handle_unknown="ignore")),
                    ]
                ),
                categorical,
            ),
        ]
    )


def train_risk_model(train_df: pd.DataFrame, val_df: pd.DataFrame) -> tuple[Pipeline, dict]:
    y_train = (train_df["approval_risk_tier"] == "High").astype(int)
    y_val = (val_df["approval_risk_tier"] == "High").astype(int)

    model = Pipeline(
        steps=[
            ("preprocess", make_preprocessor(RISK_FEATURES)),
            (
                "clf",
                LogisticRegression(
                    C=0.01,
                    penalty="l2",
                    class_weight="balanced",
                    solver="lbfgs",
                    max_iter=1000,
                    random_state=42,
                ),
            ),
        ]
    )
    model.fit(train_df[RISK_FEATURES], y_train)

    val_proba = model.predict_proba(val_df[RISK_FEATURES])[:, 1]
    val_pred = (val_proba >= 0.45).astype(int)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_val, val_pred, average="binary", zero_division=0
    )

    metrics = {
        "threshold": 0.45,
        "validation_accuracy": float((val_pred == y_val).mean()),
        "validation_precision": float(precision),
        "validation_recall": float(recall),
        "validation_f1": float(f1),
        "validation_roc_auc": float(roc_auc_score(y_val, val_proba)),
        "validation_pr_auc": float(average_precision_score(y_val, val_proba)),
    }
    return model, metrics


def train_approval_model(train_df: pd.DataFrame, val_df: pd.DataFrame) -> tuple[Pipeline, dict]:
    model = Pipeline(
        steps=[
            ("preprocess", make_preprocessor(REGRESSION_FEATURES)),
            (
                "reg",
                XGBRegressor(
                    n_estimators=200,
                    max_depth=5,
                    learning_rate=0.1,
                    subsample=1.0,
                    colsample_bytree=0.8,
                    min_child_weight=5,
                    objective="reg:squarederror",
                    random_state=42,
                    n_jobs=-1,
                ),
            ),
        ]
    )
    model.fit(train_df[REGRESSION_FEATURES], train_df["approval_rate"])

    val_pred = np.clip(model.predict(val_df[REGRESSION_FEATURES]), 0, 1)
    metrics = {
        "validation_rmse": float(mean_squared_error(val_df["approval_rate"], val_pred) ** 0.5),
        "validation_mae": float(mean_absolute_error(val_df["approval_rate"], val_pred)),
        "validation_r2": float(r2_score(val_df["approval_rate"], val_pred)),
    }
    return model, metrics


def build_lookups(df: pd.DataFrame) -> None:
    LOOKUPS_DIR.mkdir(parents=True, exist_ok=True)

    naics_lookup = (
        df.groupby("naics", dropna=True)
        .agg(
            avg_approval_rate=("approval_rate", "mean"),
            total_cases=("total_cases", "sum"),
            employer_rows=("employer_name", "count"),
            avg_total_cases=("total_cases", "mean"),
            avg_log_petitions=("log_petitions", "mean"),
            avg_initial_share=("initial_share", "mean"),
            avg_continuation_share=("continuation_share", "mean"),
            industry_mean_rate=("industry_mean_rate", "mean"),
            industry_std=("industry_std", "mean"),
            industry_cv=("industry_cv", "mean"),
            industry_employer_count=("industry_employer_count", "mean"),
            industry_total_cases=("industry_total_cases", "mean"),
            high_risk_share=("approval_risk_tier", lambda x: float((x == "High").mean())),
            risk_tier=("approval_risk_tier", lambda x: x.mode().iloc[0] if len(x.mode()) else None),
        )
        .reset_index()
    )
    naics_lookup["label"] = naics_lookup["naics"].map(lambda x: NAICS_LABELS.get(int(x), f"Industry {int(x)}"))
    naics_lookup.to_csv(LOOKUPS_DIR / "naics_stats.csv", index=False)

    state_lookup = (
        df.groupby("state", dropna=False)
        .agg(
            avg_approval_rate=("approval_rate", "mean"),
            total_cases=("total_cases", "sum"),
            employer_rows=("employer_name", "count"),
        )
        .reset_index()
    )
    state_lookup.to_csv(LOOKUPS_DIR / "state_stats.csv", index=False)

    employer_lookup = (
        df.groupby("employer_name", dropna=True)
        .agg(
            approval_rate=("approval_rate", "mean"),
            total_cases=("total_cases", "sum"),
            years_active=("fiscal_year", "nunique"),
            primary_state=("state", lambda x: x.mode().iloc[0] if len(x.mode()) else ""),
            primary_naics=("naics", lambda x: x.mode().iloc[0] if len(x.mode()) else None),
            log_petitions=("log_petitions", "mean"),
            initial_share=("initial_share", "mean"),
            continuation_share=("continuation_share", "mean"),
            risk_tier=("approval_risk_tier", lambda x: x.mode().iloc[0] if len(x.mode()) else None),
        )
        .reset_index()
    )
    employer_lookup = employer_lookup.rename(columns={"employer_name": "employer"})
    employer_lookup["employer"] = employer_lookup["employer"].astype(str).str.upper()
    employer_lookup.to_csv(LOOKUPS_DIR / "employer_stats.csv", index=False)


def main() -> None:
    df = load_dataset()
    train_df = df[df["data_split"] == "train"].copy()
    val_df = df[df["data_split"] == "validation"].copy()

    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    risk_model, risk_metrics = train_risk_model(train_df, val_df)
    approval_model, approval_metrics = train_approval_model(train_df, val_df)
    build_lookups(df)

    joblib.dump(risk_model, MODEL_DIR / "h1b_high_risk_model.joblib")
    joblib.dump(approval_model, MODEL_DIR / "h1b_approval_rate_model.joblib")
    joblib.dump(
        {
            "source_project": "H1B-Sponsorship-Analytics",
            "source_dataset": "h1b_engineered_features.csv",
            "train_years": [2021, 2022, 2023, 2024],
            "validation_year": 2025,
            "test_year": 2026,
            "risk_features": RISK_FEATURES,
            "regression_features": REGRESSION_FEATURES,
            "risk_model": "Binary Logistic Regression",
            "approval_model": "XGBoost Regressor",
            "risk_metrics": risk_metrics,
            "approval_metrics": approval_metrics,
        },
        MODEL_DIR / "model_meta.joblib",
    )

    print("[OK] Saved H1B Analytics model artifacts")
    print(f"Risk metrics: {risk_metrics}")
    print(f"Approval metrics: {approval_metrics}")


if __name__ == "__main__":
    main()
